version: "3"
services:
 web:
   image: devopstrainer/deploy:webapp
   ports:
   - "8001:80"
   depends_on:
   - db
 db:
   image: mysql:5.6
   volumes:
   - db_data:/var/lib/mysql
   environment:
     MYSQL_ROOT_PASSWORD: example
     MYSQL_DATABASE: docker
volumes:
     db_data: {}
